# Generated by Django 3.0.8 on 2020-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
    ]
