# Generated by Django 3.0.8 on 2020-07-30 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True, verbose_name='kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Rewrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=' ', verbose_name='komentarz'),
        ),
        migrations.RemoveField(
            model_name='follower',
            name='follower_user',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=255, verbose_name='nazwa przepisu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='zdjęcie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recipe',
            field=models.TextField(verbose_name='przepis'),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
        migrations.AddField(
            model_name='rewrite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='general.Post'),
        ),
        migrations.AddField(
            model_name='rewrite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='general.Category', verbose_name='kategoria'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Profile', verbose_name='użytkownik'),
        ),
        migrations.AddField(
            model_name='follower',
            name='follower_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to='general.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='general.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='general.Profile'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
