# Generated by Django 3.0.8 on 2020-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20200711_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=255, verbose_name='nazwa przepisu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='zdjęcie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recipe',
            field=models.TextField(verbose_name='przepis'),
        ),
    ]
