# Generated by Django 3.0.8 on 2020-07-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20200712_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('lunch', 'lunch'), ('śniadanie', 'śniadanie'), ('obiad', 'obiad'), ('kolacja', 'kolacja'), ('deser', 'deser'), ('wegetariańskie', 'wegetariańskie'), ('szybkie', 'szybkie'), ('mięsne', 'mięsne'), ('proste', 'proste')], max_length=20, null=True)),
                ('post', models.ManyToManyField(related_name='category', to='general.Post')),
            ],
        ),
    ]
