# Generated by Django 3.0.8 on 2020-07-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20200713_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Profile', verbose_name='użytkownik'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=' ', verbose_name='treść'),
        ),
    ]
