# Generated by Django 3.0.8 on 2020-07-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20200715_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('lunch', 'lunch'), ('śniadanie', 'śniadanie'), ('obiad', 'obiad'), ('kolacja', 'kolacja'), ('deser', 'deser'), ('wegetariańskie', 'wegetariańskie'), ('szybkie', 'szybkie'), ('mięsne', 'mięsne'), ('proste', 'proste')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
