# Generated by Django 3.0.8 on 2020-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20200716_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lunch', 'lunch'), ('śniadanie', 'śniadanie'), ('obiad', 'obiad'), ('kolacja', 'kolacja'), ('deser', 'deser'), ('wegetariańskie', 'wegetariańskie'), ('szybkie', 'szybkie'), ('mięsne', 'mięsne'), ('proste', 'proste')], max_length=20, null=True, verbose_name='kategoria')),
                ('post', models.ManyToManyField(related_name='post', to='general.Post')),
            ],
        ),
    ]
