# Generated by Django 3.0.8 on 2020-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20200717_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(related_name='category', to='general.Post'),
        ),
    ]
