# Generated by Django 3.0.8 on 2020-07-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_auto_20200720_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewrite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='general.Post'),
        ),
    ]
