# Generated by Django 3.0.8 on 2020-07-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_auto_20200721_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
