# Generated by Django 3.0.8 on 2020-07-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
