# Generated by Django 3.0.8 on 2020-07-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_delete_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
